# markdownlint-cli2 configuration
config:
  MD013:
    line_length: 120
    code_blocks: false
    tables: false
  MD022: false
  MD029: false
  MD031: false
  MD033: false
  MD034: false
  MD036: false
  MD040: false
  MD041: false
