name: ✨ Feature Request
description: Suggest a new feature or enhancement for jsonb_ivm
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe your idea in detail.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-flight checklist
      description: Please ensure you've completed these steps
      options:
        - label: I have searched existing issues and confirmed this is not a duplicate
          required: true
        - label: I have read the [API reference](https://github.com/fraiseql/jsonb_ivm/blob/main/docs/api-reference.md)
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this feature to work?
      placeholder: |
        I'd like a function that...
        Example usage:
        SELECT jsonb_new_function(...);
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions or workarounds have you considered?

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your real-world use case for this feature
      placeholder: |
        I'm building an application that...
        This feature would help by...

  - type: checkboxes
    id: scope
    attributes:
      label: Feature Scope
      description: Which areas does this feature affect?
      options:
        - label: New function (SQL API)
        - label: Performance optimization
        - label: Documentation
        - label: Testing
        - label: Build/installation
        - label: Other

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (blocking production use)
        - High (significantly improves workflow)
        - Medium (nice to have)
        - Low (minor improvement)
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Are you willing to help implement this feature?
      options:
        - label: I'm willing to submit a pull request
        - label: I can help with testing
        - label: I can help with documentation
