[32m[1m       Using[0m[39m [37m[1mCliArgument("pg17")[0m[39m and `pg_config` from [36m/home/lionel/.pgrx/17.7/pgrx-install/bin/pg_config[39m
[32m[1m    Building[0m[39m for SQL generation with features `pg17`
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.05s
[32m[1m  Discovered[0m[39m [36m[1m13[0m[39m SQL entities: [36m[1m0[0m[39m schemas ([36m[1m0[0m[39m unique), [36m[1m13[0m[39m functions, [36m[1m0[0m[39m types, [36m[1m0[0m[39m enums, [36m[1m0[0m[39m sqls, [36m[1m0[0m[39m ords, [36m[1m0[0m[39m hashes, [36m[1m0[0m[39m aggregates, [36m[1m0[0m[39m triggers
[32m[1m  Rebuilding[0m[39m [36mpgrx_embed[39m, in debug mode, for SQL generation with features [36mpg17[39m
   Compiling jsonb_ivm v0.2.0 (/home/lionel/code/jsonb_ivm)
warning: unexpected `cfg` condition name: `pgrx_embed`
 --> src/bin/pgrx_embed.rs:2:1
  |
2 | ::pgrx::pgrx_embed!();
  | ^^^^^^^^^^^^^^^^^^^^^
  |
  = help: expected names are: `docsrs`, `feature`, and `test` and 31 more
  = note: using a cfg inside a macro will use the cfgs from the destination crate and not the ones from the defining crate
  = help: try referring to `::pgrx::pgrx_embed` crate for guidance on how handle this unexpected cfg
  = help: the macro `::pgrx::pgrx_embed` may come from an old version of the `pgrx` crate, try updating your dependency with `cargo update -p pgrx`
  = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
  = note: `#[warn(unexpected_cfgs)]` on by default
  = note: this warning originates in the macro `::pgrx::pgrx_embed` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: unexpected `cfg` condition name: `pgrx_embed`
 --> src/bin/pgrx_embed.rs:2:1
  |
2 | ::pgrx::pgrx_embed!();
  | ^^^^^^^^^^^^^^^^^^^^^
  |
  = note: using a cfg inside a macro will use the cfgs from the destination crate and not the ones from the defining crate
  = help: try referring to `::pgrx::pgrx_embed` crate for guidance on how handle this unexpected cfg
  = help: the macro `::pgrx::pgrx_embed` may come from an old version of the `pgrx` crate, try updating your dependency with `cargo update -p pgrx`
  = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
  = note: this warning originates in the macro `::pgrx::pgrx_embed` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: `jsonb_ivm` (bin "pgrx_embed_jsonb_ivm") generated 2 warnings
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.19s
[32m[1m     Writing[0m[39m SQL entities to /dev/stdout
/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:1142
-- jsonb_ivm::jsonb_array_contains_id
CREATE  FUNCTION "jsonb_array_contains_id"(
	"data" jsonb, /* pgrx::datum::json::JsonB */
	"array_path" TEXT, /* &str */
	"id_key" TEXT, /* &str */
	"id_value" jsonb /* pgrx::datum::json::JsonB */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'jsonb_array_contains_id_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:722
-- jsonb_ivm::jsonb_array_delete_where
CREATE  FUNCTION "jsonb_array_delete_where"(
	"target" jsonb, /* pgrx::datum::json::JsonB */
	"array_path" TEXT, /* &str */
	"match_key" TEXT, /* &str */
	"match_value" jsonb /* pgrx::datum::json::JsonB */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'jsonb_array_delete_where_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:823
-- jsonb_ivm::jsonb_array_insert_where
CREATE  FUNCTION "jsonb_array_insert_where"(
	"target" jsonb, /* pgrx::datum::json::JsonB */
	"array_path" TEXT, /* &str */
	"new_element" jsonb, /* pgrx::datum::json::JsonB */
	"sort_key" TEXT, /* core::option::Option<&str> */
	"sort_order" TEXT /* core::option::Option<&str> */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'jsonb_array_insert_where_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:373
-- jsonb_ivm::jsonb_array_update_multi_row
CREATE  FUNCTION "jsonb_array_update_multi_row"(
	"targets" jsonb[], /* pgrx::datum::array::Array<'_, pgrx::datum::json::JsonB> */
	"array_path" TEXT, /* &str */
	"match_key" TEXT, /* &str */
	"match_value" jsonb, /* pgrx::datum::json::JsonB */
	"updates" jsonb /* pgrx::datum::json::JsonB */
) RETURNS TABLE (
	"result" jsonb  /* pgrx::datum::json::JsonB */
)
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'jsonb_array_update_multi_row_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:171
-- jsonb_ivm::jsonb_array_update_where
CREATE  FUNCTION "jsonb_array_update_where"(
	"target" jsonb, /* pgrx::datum::json::JsonB */
	"array_path" TEXT, /* &str */
	"match_key" TEXT, /* &str */
	"match_value" jsonb, /* pgrx::datum::json::JsonB */
	"updates" jsonb /* pgrx::datum::json::JsonB */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'jsonb_array_update_where_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:266
-- jsonb_ivm::jsonb_array_update_where_batch
CREATE  FUNCTION "jsonb_array_update_where_batch"(
	"target" jsonb, /* pgrx::datum::json::JsonB */
	"array_path" TEXT, /* &str */
	"match_key" TEXT, /* &str */
	"updates_array" jsonb /* pgrx::datum::json::JsonB */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'jsonb_array_update_where_batch_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:985
-- jsonb_ivm::jsonb_deep_merge
CREATE  FUNCTION "jsonb_deep_merge"(
	"target" jsonb, /* pgrx::datum::json::JsonB */
	"source" jsonb /* pgrx::datum::json::JsonB */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'jsonb_deep_merge_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:1066
-- jsonb_ivm::jsonb_extract_id
CREATE  FUNCTION "jsonb_extract_id"(
	"data" jsonb, /* pgrx::datum::json::JsonB */
	"key" TEXT DEFAULT 'id' /* &str */
) RETURNS TEXT /* core::option::Option<alloc::string::String> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'jsonb_extract_id_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:433
-- jsonb_ivm::jsonb_merge_at_path
CREATE  FUNCTION "jsonb_merge_at_path"(
	"target" jsonb, /* pgrx::datum::json::JsonB */
	"source" jsonb, /* pgrx::datum::json::JsonB */
	"path" TEXT[] /* pgrx::datum::array::Array<'_, &str> */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'jsonb_merge_at_path_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:97
-- jsonb_ivm::jsonb_merge_shallow
CREATE  FUNCTION "jsonb_merge_shallow"(
	"target" jsonb, /* core::option::Option<pgrx::datum::json::JsonB> */
	"source" jsonb /* core::option::Option<pgrx::datum::json::JsonB> */
) RETURNS jsonb /* core::option::Option<pgrx::datum::json::JsonB> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'jsonb_merge_shallow_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:660
-- jsonb_ivm::jsonb_smart_patch_array
CREATE  FUNCTION "jsonb_smart_patch_array"(
	"target" jsonb, /* pgrx::datum::json::JsonB */
	"source" jsonb, /* pgrx::datum::json::JsonB */
	"array_path" TEXT, /* &str */
	"match_key" TEXT, /* &str */
	"match_value" jsonb /* pgrx::datum::json::JsonB */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'jsonb_smart_patch_array_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:610
-- jsonb_ivm::jsonb_smart_patch_nested
CREATE  FUNCTION "jsonb_smart_patch_nested"(
	"target" jsonb, /* pgrx::datum::json::JsonB */
	"source" jsonb, /* pgrx::datum::json::JsonB */
	"path" TEXT[] /* pgrx::datum::array::Array<'_, &str> */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'jsonb_smart_patch_nested_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:570
-- jsonb_ivm::jsonb_smart_patch_scalar
CREATE  FUNCTION "jsonb_smart_patch_scalar"(
	"target" jsonb, /* pgrx::datum::json::JsonB */
	"source" jsonb /* pgrx::datum::json::JsonB */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'jsonb_smart_patch_scalar_wrapper';
/* </end connected objects> */
