/* <begin connected objects> */
/*
This file is auto generated by pgrx.

The ordering of items is not stable, it is driven by a dependency graph.
*/
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:1125
-- jsonb_ivm::jsonb_array_contains_id
CREATE  FUNCTION "jsonb_array_contains_id"(
	"data" jsonb, /* pgrx::datum::json::JsonB */
	"array_path" TEXT, /* &str */
	"id_key" TEXT, /* &str */
	"id_value" jsonb /* pgrx::datum::json::JsonB */
) RETURNS bool /* bool */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'jsonb_array_contains_id_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:699
-- jsonb_ivm::jsonb_array_delete_where
CREATE  FUNCTION "jsonb_array_delete_where"(
	"target" jsonb, /* pgrx::datum::json::JsonB */
	"array_path" TEXT, /* &str */
	"match_key" TEXT, /* &str */
	"match_value" jsonb /* pgrx::datum::json::JsonB */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'jsonb_array_delete_where_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:802
-- jsonb_ivm::jsonb_array_insert_where
CREATE  FUNCTION "jsonb_array_insert_where"(
	"target" jsonb, /* pgrx::datum::json::JsonB */
	"array_path" TEXT, /* &str */
	"new_element" jsonb, /* pgrx::datum::json::JsonB */
	"sort_key" TEXT, /* core::option::Option<&str> */
	"sort_order" TEXT /* core::option::Option<&str> */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
IMMUTABLE PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'jsonb_array_insert_where_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:370
-- jsonb_ivm::jsonb_array_update_multi_row
CREATE  FUNCTION "jsonb_array_update_multi_row"(
	"targets" jsonb[], /* pgrx::datum::array::Array<'_, pgrx::datum::json::JsonB> */
	"array_path" TEXT, /* &str */
	"match_key" TEXT, /* &str */
	"match_value" jsonb, /* pgrx::datum::json::JsonB */
	"updates" jsonb /* pgrx::datum::json::JsonB */
) RETURNS TABLE (
	"result" jsonb  /* pgrx::datum::json::JsonB */
)
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'jsonb_array_update_multi_row_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:169
-- jsonb_ivm::jsonb_array_update_where
CREATE  FUNCTION "jsonb_array_update_where"(
	"target" jsonb, /* pgrx::datum::json::JsonB */
	"array_path" TEXT, /* &str */
	"match_key" TEXT, /* &str */
	"match_value" jsonb, /* pgrx::datum::json::JsonB */
	"updates" jsonb /* pgrx::datum::json::JsonB */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'jsonb_array_update_where_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:263
-- jsonb_ivm::jsonb_array_update_where_batch
CREATE  FUNCTION "jsonb_array_update_where_batch"(
	"target" jsonb, /* pgrx::datum::json::JsonB */
	"array_path" TEXT, /* &str */
	"match_key" TEXT, /* &str */
	"updates_array" jsonb /* pgrx::datum::json::JsonB */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'jsonb_array_update_where_batch_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:967
-- jsonb_ivm::jsonb_deep_merge
CREATE  FUNCTION "jsonb_deep_merge"(
	"target" jsonb, /* pgrx::datum::json::JsonB */
	"source" jsonb /* pgrx::datum::json::JsonB */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'jsonb_deep_merge_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:1049
-- jsonb_ivm::jsonb_extract_id
CREATE  FUNCTION "jsonb_extract_id"(
	"data" jsonb, /* pgrx::datum::json::JsonB */
	"key" TEXT DEFAULT 'id' /* &str */
) RETURNS TEXT /* core::option::Option<alloc::string::String> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'jsonb_extract_id_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:425
-- jsonb_ivm::jsonb_merge_at_path
CREATE  FUNCTION "jsonb_merge_at_path"(
	"target" jsonb, /* pgrx::datum::json::JsonB */
	"source" jsonb, /* pgrx::datum::json::JsonB */
	"path" TEXT[] /* pgrx::datum::array::Array<'_, &str> */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'jsonb_merge_at_path_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:95
-- jsonb_ivm::jsonb_merge_shallow
CREATE  FUNCTION "jsonb_merge_shallow"(
	"target" jsonb, /* core::option::Option<pgrx::datum::json::JsonB> */
	"source" jsonb /* core::option::Option<pgrx::datum::json::JsonB> */
) RETURNS jsonb /* core::option::Option<pgrx::datum::json::JsonB> */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'jsonb_merge_shallow_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:637
-- jsonb_ivm::jsonb_smart_patch_array
CREATE  FUNCTION "jsonb_smart_patch_array"(
	"target" jsonb, /* pgrx::datum::json::JsonB */
	"source" jsonb, /* pgrx::datum::json::JsonB */
	"array_path" TEXT, /* &str */
	"match_key" TEXT, /* &str */
	"match_value" jsonb /* pgrx::datum::json::JsonB */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'jsonb_smart_patch_array_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:591
-- jsonb_ivm::jsonb_smart_patch_nested
CREATE  FUNCTION "jsonb_smart_patch_nested"(
	"target" jsonb, /* pgrx::datum::json::JsonB */
	"source" jsonb, /* pgrx::datum::json::JsonB */
	"path" TEXT[] /* pgrx::datum::array::Array<'_, &str> */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'jsonb_smart_patch_nested_wrapper';
/* </end connected objects> */

/* <begin connected objects> */
-- src/lib.rs:554
-- jsonb_ivm::jsonb_smart_patch_scalar
CREATE  FUNCTION "jsonb_smart_patch_scalar"(
	"target" jsonb, /* pgrx::datum::json::JsonB */
	"source" jsonb /* pgrx::datum::json::JsonB */
) RETURNS jsonb /* pgrx::datum::json::JsonB */
IMMUTABLE STRICT PARALLEL SAFE
LANGUAGE c /* Rust */
AS 'MODULE_PATHNAME', 'jsonb_smart_patch_scalar_wrapper';
/* </end connected objects> */

